name: Telegram Scraper Notification

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 min
  workflow_dispatch:

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper and send Telegram message
        run: |
          python src/scraper.py
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_API: ${{ secrets.BOT_API }}
